# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest

# Environment variables for PostgreSQL configuration
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword
ENV POSTGRES_DB=mydatabase

# Expose the PostgreSQL default port
EXPOSE 5432
