version: '3'

services:
  ntp:
    image: .
    container_name: my-ntp-container
    command: ["chronyd", "-d", "-s"]
    ports:
      - "123:123/udp"
    volumes:
      - ./chrony.conf:/etc/chrony/chrony.conf
